In [1]:
print("hello")

hello

In [2]:
import sqlite3 
import pandas as pd

conn = sqlite3.connect("../data/paysim.db")

In [4]:
query = """
SELECT type, Count(*) AS total_txns
from transactions
Group BY type
"""
pd.read_sql(query, conn)

       type  total_txns
0   CASH_IN     1399284
1  CASH_OUT     2237500
2     DEBIT       41432
3   PAYMENT     2151495
4  TRANSFER      532909

In [9]:
query = """

SELECT type, nameOrig,amount, step
from transactions
where isFraud = 1 
order by amount DESC
LIMIT 10
"""
pd.read_sql(query, conn)

       type     nameOrig      amount  step
0  TRANSFER     C7162498  10000000.0     4
1  CASH_OUT   C351297720  10000000.0     4
2  TRANSFER   C416779475  10000000.0    19
3  CASH_OUT  C2050703310  10000000.0    19
4  TRANSFER  C1439740840  10000000.0    33
5  CASH_OUT    C29118015  10000000.0    33
6  TRANSFER    C53057884  10000000.0    72
7  CASH_OUT  C1438388258  10000000.0    72
8  TRANSFER  C1237313447  10000000.0    82
9  CASH_OUT  C1079335762  10000000.0    82

“Fraudulent [type] transactions are on average [bigger/smaller] than normal ones ([number] vs [number]).”

In [10]:
query = """

select type,isFraud, AVG(amount) AS avg_amount
from transactions
where type IN ('TRANSFER', 'CASH_OUT')
Group by type, isFraud
order by type, isFraud
"""
pd.read_sql(query,conn)

       type  isFraud    avg_amount
0  CASH_OUT        0  1.739172e+05
1  CASH_OUT        1  1.455103e+06
2  TRANSFER        0  9.062290e+05
3  TRANSFER        1  1.480892e+06

In [14]:
query = """
SELECT type,
       isFraud,
       COUNT(*) AS total_txns,
       SUM(CASE WHEN newbalanceOrig = 0 THEN 1 ELSE 0 END) AS emptied_accounts,
       ROUND(100.0 * SUM(CASE WHEN newbalanceOrig = 0 THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_emptied
FROM transactions
WHERE type IN ('TRANSFER', 'CASH_OUT')
GROUP BY type, isFraud
ORDER BY type, isFraud
"""
pd.read_sql(query, conn)

DatabaseError: Execution failed on sql '

select type,
isFraud,
Count(*) AS total_txns,
SUM(CASE WHEN newbalanceOrig = 0 THEN 1 ELSE 0 END) AS emptied_accounts,
ROUND(100.0 * SUM(CASE WHEN newbalanceOrig = 0 THEN 1 ELSE 0 END)) / COUNT(*),2) as pct_emptied
from transactions
where type IN('TRANSFER', 'CASH_OUT')
GROUP BY type, isFraud
ORDER BY type, isFraud
': near ")": syntax error